INSERT INTO PRODUTO(NOME, VALOR) VALUES('GELADEIRA', 1.345);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('SOFÁ', 2.345);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('ARMÁRIO', 345);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('CADEIRA', 1.045);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('CAMA', 800);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('CELULAR', 8.777);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('VENTILADOR', 80);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('TELEVISÃO', 4.654);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('VIDEO-GAME', 5.000);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('SOM', 3.988);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('BATEDEIRA', 345);

